### ISSUE TITLE
Crashing whole server after when new players create any island fix this 

### ISSUE THREAD

**Issue by RealBJsingh** [andresbytes/SkyBlock#221] opened 2020-10-23 06:28 UTC
[Fri_Oct_23-03.31.57-UTC_2020.log.txt](https://github.com/andresbytes/SkyBlock/files/5427689/Fri_Oct_23-03.31.57-UTC_2020.log.txt)

**Comment by Diduhless** [comment] 2020-10-23 14:08
How did you reproduce the error? Can you try reproducing it without any external plugins?

**Comment by RealBJsingh** [comment] 2020-10-23 15:39
I check all other plugins their is no else plugin leading to make the server crash u can see crash log its only happening after we have 1k+ islands

**Comment by RealBJsingh** [comment] 2020-10-28 07:05
[07:01:26] [Server thread/CRITICAL]: Error: "Class name must be a valid object or a string" (EXCEPTION) in "plugins/SkyBlock (3).phar/src/room17/SkyBlock/island/IslandListener" at line 236 


Also ignoring is not a way to improve plugin this now happened in new server also

**Comment by Diduhless** [comment] 2020-11-05 00:22
This problem may have been fixed with 6a0a53cf3178970a0608e7d1101f285ea462d778
I'm not able to reproduce the issue by myself, could you check if the latest version works for you?
https://poggit.pmmp.io/ci/andresbytes/SkyBlock/SkyBlock/dev:176

**Comment by andresbytes** [comment] 2020-12-01 22:17
is anyone still having this issue?

**Closed** 2020-12-05 14:18 UTC
Labels: Status: Reproduced, Type: Bug
